version: '3.8'
services:
  arachni:
    image: 'csalab/arachni:latest'
    hostname: arachni.lab
    restart: always
    build:
      context: ./build/
      dockerfile: arachni.Dockerfile
    volumes:
      - arachni:/opt/arachni
    networks:
      dast:

  dast-ci:
    image: 'csalab/dast:latest'
    hostname: dast.lab
    restart: always
    build:
      context: ./build/
      dockerfile: dast-ci.Dockerfile
    networks:
      dast:

networks:
  dast:
    driver: bridge

volumes:
  arachni: {}